### ISSUE TITLE
Material Skin error CS0246

### ISSUE THREAD

**Issue by aHeats** [Sehyn/Mastralis-Kurtzpel#2]
1>C:\Users\User\Desktop\Mastralis-Kurtzpel-master\Mastralis-Kurtzpel-master\Mastralis\Mastralis.Designer.cs(683,17,683,29): error CS0246: The type or namespace name 'MaterialSkin' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Sehyn** [comment]
![image](https://user-images.githubusercontent.com/48888351/59638588-1dd31380-9159-11e9-8a11-88f75156820d.png)
![image](https://user-images.githubusercontent.com/48888351/59638656-32afa700-9159-11e9-9704-63df5e12df79.png)
